//
//  QuizQuestion.swift
//  Swift Quiz Academy
//

import Foundation

struct QuizQuestion {
    let questionBG: String
    let questionEN: String
    let answersBG: [String]
    let answersEN: [String]
    let correctAnswerBG: Int
    let correctAnswerEN: Int

    var text: String {
        questionEN
    }

    var answers: [String] {
        answersEN
    }

    var correctAnswerIndex: Int {
        correctAnswerEN
    }

    init(
        questionBG: String,
        questionEN: String,
        answersBG: [String],
        answersEN: [String],
        correctAnswerBG: Int,
        correctAnswerEN: Int
    ) {
        self.questionBG = questionBG
        self.questionEN = questionEN
        self.answersBG = answersBG
        self.answersEN = answersEN
        self.correctAnswerBG = correctAnswerBG
        self.correctAnswerEN = correctAnswerEN
    }

    init(text: String, answers: [String], correctAnswerIndex: Int) {
        questionEN = text
        questionBG = Self.localizedBulgarianQuestion(for: text)
        answersEN = answers
        answersBG = answers.map { answer in
            Self.localizedBulgarianAnswer(answer)
        }
        correctAnswerEN = correctAnswerIndex
        correctAnswerBG = correctAnswerIndex
    }

    func questionText(for language: AppLanguage) -> String {
        switch language {
        case .bulgarian:
            return questionBG
        case .english:
            return questionEN
        }
    }

    func answers(for language: AppLanguage) -> [String] {
        switch language {
        case .bulgarian:
            return answersBG
        case .english:
            return answersEN
        }
    }

    func correctAnswerIndex(for language: AppLanguage) -> Int {
        switch language {
        case .bulgarian:
            return correctAnswerBG
        case .english:
            return correctAnswerEN
        }
    }

    func correctAnswerText(for language: AppLanguage) -> String {
        let localizedAnswers = answers(for: language)
        let index = correctAnswerIndex(for: language)
        guard localizedAnswers.indices.contains(index) else { return "" }
        return localizedAnswers[index]
    }

    func explanationText(for language: AppLanguage) -> String {
        let correctAnswer = correctAnswerText(for: language)

        switch language {
        case .bulgarian:
            return "Правилният отговор е \"\(correctAnswer)\". Това е ключовата идея зад въпроса и е важно да я разпознаваш, когато пишеш Swift код."
        case .english:
            return "The correct answer is \"\(correctAnswer)\". This is the key idea behind the question and it is important to recognize it when writing Swift code."
        }
    }

    private static func localizedBulgarianQuestion(for text: String) -> String {
        questionTranslations[text] ?? text
    }

    private static func localizedBulgarianAnswer(_ answer: String) -> String {
        answerTranslations[answer] ?? answer
    }

    private static let questionTranslations: [String: String] = [
        "Which keyword creates a constant in Swift?": "Коя ключова дума създава константа в Swift?",
        "Which type stores whole numbers?": "Кой тип съхранява цели числа?",
        "How do you define a function in Swift?": "Как се дефинира функция в Swift?",
        "Which operator checks equality?": "Кой оператор проверява равенство?",
        "Which type represents true or false?": "Кой тип представя истина или лъжа?",
        "Which keyword creates a variable?": "Коя ключова дума създава променлива?",
        "What does nil mean in Swift?": "Какво означава nil в Swift?",
        "Which syntax creates an optional String?": "Кой синтаксис създава Optional String?",
        "Which collection keeps ordered values?": "Коя колекция пази подредени стойности?",
        "What keyword returns a value from a function?": "Коя ключова дума връща стойност от функция?",
        "Which protocol does a SwiftUI screen usually conform to?": "Към кой протокол обикновено се conform-ва SwiftUI екран?",
        "Which property provides the UI content of a View?": "Кое property предоставя UI съдържанието на View?",
        "Which wrapper stores local view state?": "Кой wrapper пази локално състояние на view?",
        "Which view arranges children vertically?": "Кой view подрежда елементи вертикално?",
        "Which view overlays children on top of each other?": "Кой view наслагва елементи един върху друг?",
        "Which modifier adds space inside a view?": "Кой modifier добавя вътрешно разстояние във view?",
        "Which view shows tappable text or content?": "Кой view показва съдържание, върху което може да се натисне?",
        "Which view displays SF Symbols?": "Кой view показва SF Symbols?",
        "Which modifier changes font style?": "Кой modifier променя стила на шрифта?",
        "Which view creates empty flexible space?": "Кой view създава празно гъвкаво пространство?",
        "What is Xcode used for?": "За какво се използва Xcode?",
        "What file usually launches a SwiftUI app?": "Кой файл обикновено стартира SwiftUI приложение?",
        "Where are app images commonly stored?": "Къде обикновено се съхраняват изображенията на приложението?",
        "What is a simulator?": "Какво е simulator?",
        "Which language is commonly used for modern iOS apps?": "Кой език често се използва за модерни iOS приложения?",
        "What is an app icon?": "Какво е app icon?",
        "What does build mean in Xcode?": "Какво означава build в Xcode?",
        "Which area shows compile problems?": "Коя зона показва проблеми при компилация?",
        "What is a Preview in SwiftUI?": "Какво е Preview в SwiftUI?",
        "What does UI stand for?": "Какво означава UI?",
        "Which statement runs code only when a condition is true?": "Кой statement изпълнява код само когато условието е вярно?",
        "Which loop repeats over items in a collection?": "Кой цикъл минава през елементи в колекция?",
        "What does && mean in a condition?": "Какво означава && в условие?",
        "What does || mean in a condition?": "Какво означава || в условие?",
        "Which operator means not equal?": "Кой оператор означава различно?",
        "What is an algorithm?": "Какво е алгоритъм?",
        "What happens when a loop condition never becomes false?": "Какво става, когато условието на цикъл никога не става false?",
        "Which statement chooses between multiple cases?": "Кой statement избира между множество случаи?",
        "What is debugging?": "Какво е debugging?",
        "What should a Boolean expression produce?": "Какво трябва да връща Boolean expression?",
        "What does AI stand for?": "Какво означава AI?",
        "What is machine learning?": "Какво е машинно обучение?",
        "What is a model in AI?": "Какво е модел в AI?",
        "What is training data?": "Какво са training data?",
        "What is a prompt?": "Какво е prompt?",
        "What is classification?": "Какво е classification?",
        "What is prediction?": "Какво е prediction?",
        "What is natural language?": "Какво е natural language?",
        "Why can AI make mistakes?": "Защо AI може да греши?",
        "What is responsible AI about?": "Какво означава responsible AI?",
        "Daily Swift: Which keyword creates an immutable value?": "Дневен Swift: Коя ключова дума създава неизменима стойност?",
        "Daily SwiftUI: Which wrapper stores simple local state?": "Дневен SwiftUI: Кой wrapper пази просто локално състояние?",
        "Daily iOS: What does a Preview help you inspect?": "Дневен iOS: Какво ти помага да прегледаш Preview?",
        "Daily Logic: What does an if statement use?": "Дневна логика: Какво използва if statement?",
        "Daily AI: What is a prompt?": "Дневен AI: Какво е prompt?",
        "Daily Swift: Which collection stores key-value pairs?": "Дневен Swift: Коя колекция пази двойки ключ-стойност?",
        "Daily SwiftUI: Which layout places views horizontally?": "Дневен SwiftUI: Кой layout подрежда views хоризонтално?",
        "Daily iOS: What is the simulator used for?": "Дневен iOS: За какво се използва simulator?",
        "Daily Logic: What does == check?": "Дневна логика: Какво проверява ==?",
        "Daily AI: Why should AI output be checked?": "Дневен AI: Защо трябва да проверяваме AI output?",
        "What does type inference allow Swift to do?": "Какво позволява type inference на Swift?",
        "Which keyword marks a method that changes a struct property?": "Коя ключова дума маркира метод, който променя property на struct?",
        "What does optional binding with if let do?": "Какво прави optional binding с if let?",
        "Which collection stores unique unordered values?": "Коя колекция пази уникални неподредени стойности?",
        "What is a tuple useful for?": "За какво е полезен tuple?",
        "Which access level keeps code usable only inside the same file?": "Кой access level прави кода използваем само в същия файл?",
        "What does guard usually help with?": "С какво обикновено помага guard?",
        "Which syntax defines a closure parameter?": "Кой синтаксис дефинира closure parameter?",
        "What does append do on an Array?": "Какво прави append върху Array?",
        "Which keyword defines a custom value type?": "Коя ключова дума дефинира custom value type?",
        "What problem do generics solve?": "Какъв проблем решават generics?",
        "What does associatedtype define in a protocol?": "Какво дефинира associatedtype в protocol?",
        "Which feature helps avoid reference cycles?": "Коя функция помага да избегнем reference cycles?",
        "What does throwing function syntax include?": "Какво включва синтаксисът на throwing function?",
        "What does async await model?": "Какво моделира async/await?",
        "What does value semantics mean for structs?": "Какво означава value semantics при structs?",
        "What is protocol-oriented programming?": "Какво е protocol-oriented programming?",
        "What can extensions add?": "Какво могат да добавят extensions?",
        "What does defer do?": "Какво прави defer?",
        "What does Result<Success, Failure> represent?": "Какво представя Result<Success, Failure>?",
        "What does @Binding allow a child view to do?": "Какво позволява @Binding на child view?",
        "Which modifier changes a view's foreground color/style?": "Кой modifier променя foreground цвета/стила на view?",
        "What is the purpose of NavigationStack?": "Каква е целта на NavigationStack?",
        "Which container efficiently shows rows of data?": "Кой container показва ефективно редове с данни?",
        "What does .sheet present?": "Какво представя .sheet?",
        "Which wrapper reads system values like color scheme?": "Кой wrapper чете system values като color scheme?",
        "What does ForEach need for dynamic data?": "От какво има нужда ForEach за dynamic data?",
        "Which modifier clips a view to a shape?": "Кой modifier изрязва view към shape?",
        "What does .disabled(true) do?": "Какво прави .disabled(true)?",
        "Which view draws a progress indicator?": "Кой view рисува progress indicator?",
        "Why should view body stay lightweight?": "Защо body на view трябва да остане лек?",
        "What does identity affect in SwiftUI lists?": "На какво влияе identity в SwiftUI lists?",
        "What does @StateObject preserve?": "Какво запазва @StateObject?",
        "What does @ObservedObject imply?": "Какво означава @ObservedObject?",
        "What does PreferenceKey help pass?": "Какво помага да се предава PreferenceKey?",
        "What is a custom Layout used for?": "За какво се използва custom Layout?",
        "What does transaction control?": "Какво контролира transaction?",
        "What can matchedGeometryEffect create?": "Какво може да създаде matchedGeometryEffect?",
        "Why avoid heavy work directly in body?": "Защо да избягваме тежка работа директно в body?",
        "What does EquatableView help with?": "С какво помага EquatableView?",
        "What is a bundle identifier used for?": "За какво се използва bundle identifier?",
        "What does Info.plist commonly store?": "Какво обикновено пази Info.plist?",
        "What is the App lifecycle about?": "За какво е App lifecycle?",
        "What does provisioning relate to?": "С какво е свързан provisioning?",
        "Which framework is used for notifications?": "Кой framework се използва за notifications?",
        "What is sandboxing on iOS?": "Какво е sandboxing в iOS?",
        "What is TestFlight used for?": "За какво се използва TestFlight?",
        "What does localization support?": "Какво поддържа localization?",
        "What is a target in Xcode?": "Какво е target в Xcode?",
        "What is an entitlement?": "Какво е entitlement?",
        "What does code signing prove?": "Какво доказва code signing?",
        "What is background execution limited by?": "От какво е ограничено background execution?",
        "Why request permissions at runtime?": "Защо се искат permissions по време на runtime?",
        "What does Keychain store best?": "Какво е най-подходящо да пази Keychain?",
        "What does App Transport Security encourage?": "Какво насърчава App Transport Security?",
        "What is a deep link?": "Какво е deep link?",
        "What is memory pressure?": "Какво е memory pressure?",
        "What does Instruments help analyze?": "Какво помага да анализираме Instruments?",
        "What is accessibility support for?": "За какво е accessibility support?",
        "What does universal link use?": "Какво използва universal link?",
        "What does decomposition mean?": "Какво означава decomposition?",
        "What is a variable's scope?": "Какво е scope на променлива?",
        "What does short-circuit evaluation do?": "Какво прави short-circuit evaluation?",
        "Which data structure works first-in, first-out?": "Коя data structure работи first-in, first-out?",
        "Which data structure works last-in, first-out?": "Коя data structure работи last-in, first-out?",
        "What is a base case in recursion?": "Какво е base case в recursion?",
        "What does sorting do?": "Какво прави sorting?",
        "What is a precondition?": "Какво е precondition?",
        "What does modulo (%) return?": "Какво връща modulo (%)?",
        "What is an edge case?": "Какво е edge case?",
        "What is Big O notation used for?": "За какво се използва Big O notation?",
        "What does O(1) mean?": "Какво означава O(1)?",
        "What does binary search require?": "Какво изисква binary search?",
        "What is a graph made of?": "От какво е съставен graph?",
        "What is dynamic programming often used for?": "За какво често се използва dynamic programming?",
        "What does immutability help reduce?": "Какво помага да намалим immutability?",
        "What is a race condition?": "Какво е race condition?",
        "What is memoization?": "Какво е memoization?",
        "What does idempotent mean?": "Какво означава idempotent?",
        "What is a state machine?": "Какво е state machine?",
        "What is overfitting?": "Какво е overfitting?",
        "What is inference in AI?": "Какво е inference в AI?",
        "What is a token in language models?": "Какво е token в language models?",
        "What is bias in data?": "Какво е bias в данните?",
        "What is validation data used for?": "За какво се използват validation data?",
        "What is a neural network inspired by?": "От какво е вдъхновена neural network?",
        "What is embeddings used for?": "За какво се използват embeddings?",
        "What is hallucination in AI?": "Какво е hallucination в AI?",
        "What is supervised learning?": "Какво е supervised learning?",
        "What is a confidence score?": "Какво е confidence score?",
        "What is temperature in text generation?": "Какво е temperature при генериране на текст?",
        "What is retrieval augmented generation?": "Какво е retrieval augmented generation?",
        "What does fine-tuning usually change?": "Какво обикновено променя fine-tuning?",
        "What is a confusion matrix useful for?": "За какво е полезна confusion matrix?",
        "What is precision?": "Какво е precision?",
        "What is recall?": "Какво е recall?",
        "What is context window?": "Какво е context window?",
        "What is model evaluation?": "Какво е model evaluation?",
        "What is prompt injection?": "Какво е prompt injection?",
        "Why use human review for high-risk AI output?": "Защо се използва human review при high-risk AI output?"
    ]

    private static let answerTranslations: [String: String] = [
        "A condition": "Условие",
        "A trained system that makes predictions": "Обучена система, която прави прогнози",
        "A step-by-step solution": "Решение стъпка по стъпка",
        "A tool that runs apps like a device": "Инструмент, който стартира приложения като устройство",
        "Adds an element": "Добавя елемент",
        "AND": "И",
        "App struct": "App struct",
        "Array": "Array",
        "Assets.xcassets": "Assets.xcassets",
        "Bool": "Bool",
        "Button": "Button",
        "Choosing a category": "Избиране на категория",
        "Compile and prepare the app": "Компилира и подготвя приложението",
        "Constant time": "Константно време",
        "Dictionary": "Dictionary",
        "Divider": "Divider",
        "Empty array": "Празен масив",
        "Estimating an output": "Оценяване на резултат",
        "Examples used to teach a model": "Примери, използвани за обучение на модел",
        "Finding and fixing problems": "Намиране и поправяне на проблеми",
        "func greet()": "func greet()",
        "HStack": "HStack",
        "Human language like English": "Човешки език като английски",
        "Image(systemName:)": "Image(systemName:)",
        "Input given to an AI system": "Вход, подаден към AI система",
        "Int": "Int",
        "List": "List",
        "No value": "Липса на стойност",
        "OR": "ИЛИ",
        "ProgressView": "ProgressView",
        "Set": "Set",
        "Spacer": "Spacer",
        "String": "String",
        "String?": "String?",
        "Swift": "Swift",
        "Systems learning patterns from data": "Системи, които учат модели от данни",
        "true or false": "true или false",
        "User Interface": "Потребителски интерфейс",
        "Using AI safely and fairly": "Използване на AI безопасно и справедливо",
        "VStack": "VStack",
        "View": "View",
        "ZStack": "ZStack",
        "Zero": "Нула",
        "var": "var",
        "let": "let",
        "func": "func",
        "class": "class",
        "String!": "String!",
        "String.nil": "String.nil",
        "Enum": "Enum",
        "send": "send",
        "return": "return",
        "break": "break",
        "yield": "yield",
        "static": "static",
        "mutating": "mutating",
        "override": "override",
        "lazy": "lazy",
        "throws": "throws",
        "error": "error",
        "catching": "catching",
        "failed": "failed",
        "weak references": "weak references",
        "for loops": "for loops",
        "arrays": "arrays",
        "tuples": "tuples",
        "Guess a type from the assigned value": "Отгатва типа от зададената стойност",
        "Skip compilation": "Пропуска компилацията",
        "Convert all values to String": "Конвертира всички стойности към String",
        "Ignore optionals": "Игнорира optional-и",
        "Safely unwraps an optional": "Безопасно unwrap-ва optional",
        "Creates a loop": "Създава цикъл",
        "Builds a class": "Създава class",
        "Sorts an array": "Сортира array",
        "Grouping multiple values together": "Групира няколко стойности заедно",
        "Only networking": "Само networking",
        "Deleting variables": "Изтриване на променливи",
        "Creating icons": "Създаване на икони",
        "public": "public",
        "private": "private",
        "fileprivate": "fileprivate",
        "open": "open",
        "Early exit when a condition fails": "Ранно излизане, когато условие не е изпълнено",
        "Drawing shapes": "Рисуване на shapes",
        "Importing assets": "Импортиране на assets",
        "Running animations only": "Стартиране само на animations",
        "{ value in ... }": "{ value in ... }",
        "func value =>": "func value =>",
        "class value": "class value",
        "import value": "import value",
        "Removes all values": "Премахва всички стойности",
        "Sorts descending": "Сортира низходящо",
        "Creates an optional": "Създава optional",
        "struct": "struct",
        "package": "package",
        "screen": "screen",
        "asset": "asset",
        "Writing reusable code for multiple types": "Писане на преизползваем код за много типове",
        "Avoiding all types": "Избягване на всички типове",
        "Skipping tests": "Пропускане на тестове",
        "A placeholder type chosen by conformers": "Placeholder тип, избран от conformer-ите",
        "A fixed String": "Фиксиран String",
        "An app icon": "Икона на приложение",
        "A stored property only": "Само stored property",
        "Asynchronous work with suspension points": "Асинхронна работа със suspension points",
        "Only animations": "Само animations",
        "Only strings": "Само strings",
        "Only dictionaries": "Само dictionaries",
        "Copies are independent values": "Копията са независими стойности",
        "All structs are global": "Всички structs са global",
        "They cannot have methods": "Не могат да имат methods",
        "They are always optional": "Винаги са optional",
        "Designing around protocols and conformances": "Дизайн около protocols и conformances",
        "Only using classes": "Използване само на classes",
        "Avoiding extensions": "Избягване на extensions",
        "Writing no types": "Писане без типове",
        "Methods, computed properties, and conformances": "Methods, computed properties и conformances",
        "Stored properties always": "Stored properties винаги",
        "New app targets": "Нови app targets",
        "Only comments": "Само comments",
        "Runs code when leaving scope": "Изпълнява код при излизане от scope",
        "Starts a task immediately": "Стартира task веднага",
        "Deletes memory": "Изтрива memory",
        "Creates a class": "Създава class",
        "Success or failure as a value": "Success или failure като стойност",
        "Only an integer": "Само integer",
        "A SwiftUI layout": "SwiftUI layout",
        "An asset catalog": "Asset catalog",
        "@State": "@State",
        "@Binding": "@Binding",
        "@SceneStorage": "@SceneStorage",
        "@Environment": "@Environment",
        "The app UI": "UI на приложението",
        "Only network logs": "Само network logs",
        "App Store reviews": "App Store reviews",
        "Device storage": "Device storage",
        "Only an image": "Само image",
        "A file path": "File path",
        "A package name": "Package name",
        "A screen size": "Размер на екрана",
        "Running apps like a device": "Стартиране на apps като на устройство",
        "Writing emails": "Писане на имейли",
        "Editing icons only": "Редактиране само на икони",
        "Deleting code": "Изтриване на код",
        "Equality": "Равенство",
        "Assignment": "Присвояване",
        "Importing": "Импортиране",
        "Looping": "Looping",
        "It can make mistakes": "Може да прави грешки",
        "It never uses data": "Никога не използва данни",
        "It cannot answer": "Не може да отговаря",
        "It only draws UI": "Само рисува UI",
        "@Local": "@Local",
        "@View": "@View",
        "@Store": "@Store",
        "Grid": "Grid",
        "Form": "Form",
        "padding()": "padding()",
        "border()": "border()",
        "clipShape()": "clipShape()",
        "offset()": "offset()",
        "Text": "Text",
        "SymbolView": "SymbolView",
        "Icon": "Icon",
        ".font()": ".font()",
        ".tint()": ".tint()",
        ".task()": ".task()",
        ".tag()": ".tag()",
        "Group": "Group",
        "Section": "Section",
        "Read and write state owned elsewhere": "Чете и променя state, притежаван другаде",
        "Create a database": "Създава database",
        "Disable previews": "Изключва previews",
        "Import images": "Импортира images",
        "foregroundStyle": "foregroundStyle",
        "padding": "padding",
        "task": "task",
        "tag": "tag",
        "Managing navigation paths": "Управляване на navigation paths",
        "Storing passwords": "Пазене на passwords",
        "Drawing charts only": "Рисуване само на charts",
        "Compiling assets": "Компилиране на assets",
        "Circle": "Circle",
        "A modal view": "Modal view",
        "A new compiler": "Нов compiler",
        "An image asset": "Image asset",
        "A unit test": "Unit test",
        "@Main": "@Main",
        "Identifiable data or an id": "Identifiable данни или id",
        "Only images": "Само images",
        "A timer": "Timer",
        "A database": "Database",
        "clipShape": "clipShape",
        "font": "font",
        "Prevents interaction": "Спира interaction",
        "Deletes a view": "Изтрива view",
        "Changes app icon": "Променя app icon",
        "Starts navigation": "Стартира navigation",
        "It can be recomputed often": "Може да се преизчислява често",
        "It runs only once ever": "Изпълнява се само веднъж",
        "It stores databases": "Пази databases",
        "It signs apps": "Подписва apps",
        "Diffing, updates, and animations": "Diffing, updates и animations",
        "Only colors": "Само colors",
        "Only network calls": "Само network calls",
        "Only app icons": "Само app icons",
        "An observable object owned by the view": "Observable object, притежаван от view",
        "A local Int only": "Само локален Int",
        "A static color": "Статичен color",
        "A system image": "System image",
        "The object is owned elsewhere": "Object-ът се притежава другаде",
        "The view owns it permanently": "View го притежава постоянно",
        "It is a constant": "Това е constant",
        "It is not observable": "Не е observable",
        "Child view values upward": "Стойности от child view нагоре",
        "Passwords": "Passwords",
        "Assets": "Assets",
        "Build settings": "Build settings",
        "Defining measurement and placement": "Дефиниране на measurement и placement",
        "Saving UserDefaults": "Запазване в UserDefaults",
        "Creating tests": "Създаване на tests",
        "Signing apps": "Подписване на apps",
        "Animation details for state changes": "Animation детайли за state changes",
        "Database rows": "Database rows",
        "App target names": "App target names",
        "Image compression": "Image compression",
        "Smooth transitions between related views": "Плавни transitions между свързани views",
        "Network requests": "Network requests",
        "Compile errors": "Compile errors",
        "User accounts": "User accounts",
        "It can hurt rendering performance": "Може да влоши rendering performance",
        "Body never reruns": "Body никога не се изпълнява повторно",
        "It disables buttons": "Изключва buttons",
        "It deletes state": "Изтрива state",
        "Skipping unchanged view updates": "Пропускане на непроменени view updates",
        "Sorting arrays": "Сортиране на arrays",
        "Building Apple apps": "Създаване на Apple apps",
        "Editing photos": "Редактиране на снимки",
        "Managing passwords": "Управляване на passwords",
        "Browsing files only": "Само разглеждане на files",
        "README": "README",
        "Asset catalog": "Asset catalog",
        "Preview": "Preview",
        "A fake API": "Fake API",
        "A compiler error": "Compiler error",
        "A cloud database": "Cloud database",
        "PHP": "PHP",
        "SQL": "SQL",
        "HTML only": "Само HTML",
        "The launch image shown on the Home Screen": "Launch image, показан на Home Screen",
        "A data type": "Data type",
        "A network call": "Network call",
        "Delete the app": "Изтрива приложението",
        "Change the language": "Променя езика",
        "Open Safari": "Отваря Safari",
        "Issue Navigator": "Issue Navigator",
        "Color Picker": "Color Picker",
        "Calendar": "Calendar",
        "Photos": "Photos",
        "A live UI render in Xcode": "Live UI render в Xcode",
        "A file format": "File format",
        "A keyboard shortcut": "Keyboard shortcut",
        "Uniquely identifying an app": "Уникално идентифициране на app",
        "Changing font size": "Промяна на font size",
        "Making loops": "Създаване на loops",
        "App configuration metadata": "App configuration metadata",
        "Only quiz answers": "Само quiz answers",
        "Swift functions": "Swift functions",
        "Compiled binaries": "Compiled binaries",
        "How an app starts, runs, and stops": "Как app стартира, работи и спира",
        "Only icons": "Само icons",
        "Only tests": "Само tests",
        "Signing and running apps on devices": "Подписване и стартиране на apps на устройства",
        "Creating arrays": "Създаване на arrays",
        "Changing text": "Промяна на text",
        "Writing loops": "Писане на loops",
        "UserNotifications": "UserNotifications",
        "MapKit": "MapKit",
        "Foundation only": "Само Foundation",
        "Apps have isolated storage and permissions": "Apps имат изолирано storage и permissions",
        "Apps can edit all files": "Apps могат да редактират всички files",
        "Apps skip signing": "Apps пропускат signing",
        "Apps cannot store data": "Apps не могат да пазят data",
        "Beta testing apps": "Beta testing на apps",
        "Writing functions": "Писане на functions",
        "Making assets": "Създаване на assets",
        "Multiple languages and regions": "Множество езици и региони",
        "Only dark mode": "Само dark mode",
        "A build product configuration": "Build product configuration",
        "A Swift loop": "Swift loop",
        "A button style": "Button style",
        "A color asset": "Color asset",
        "A permission/capability for app services": "Permission/capability за app services",
        "A question type": "Question type",
        "A view modifier": "View modifier",
        "A number type": "Number type",
        "The app comes from an identified developer": "App идва от идентифициран developer",
        "The UI is blue": "UI е син",
        "The app has no bugs": "App няма bugs",
        "The app uses SwiftUI": "App използва SwiftUI",
        "System policies and capabilities": "System policies и capabilities",
        "Only array length": "Само array length",
        "Only font size": "Само font size",
        "Only app name": "Само app name",
        "To get user consent for protected data": "За да получим user consent за protected data",
        "To compile faster": "За по-бърза компилация",
        "To create structs": "За създаване на structs",
        "To draw gradients": "За рисуване на gradients",
        "Sensitive credentials": "Sensitive credentials",
        "Large videos": "Големи videos",
        "All source files": "Всички source files",
        "Preview code": "Preview code",
        "Secure network connections": "Сигурни network connections",
        "More animations": "Повече animations",
        "Bigger icons": "По-големи icons",
        "No optionals": "Без optionals",
        "A link that opens a specific app location": "Link, който отваря конкретно място в app",
        "A nested loop": "Nested loop",
        "A large image": "Голям image",
        "A compiler feature": "Compiler feature",
        "The system needs apps to reduce memory use": "System има нужда apps да намалят memory use",
        "A syntax error": "Syntax error",
        "A missing icon": "Липсваща icon",
        "A type mismatch only": "Само type mismatch",
        "Performance and resource usage": "Performance и resource usage",
        "Only quiz text": "Само quiz text",
        "Only localization": "Само localization",
        "Making apps usable by more people": "Прави apps използваеми от повече хора",
        "Hiding UI": "Скриване на UI",
        "Reducing all text": "Намаляване на целия text",
        "Associated domains to open app content": "Associated domains за отваряне на app content",
        "Only local variables": "Само local variables",
        "Only previews": "Само previews",
        "Only SF Symbols": "Само SF Symbols",
        "if": "if",
        "import": "import",
        "for-in": "for-in",
        "switch": "switch",
        "guard": "guard",
        "NOT": "НЕ",
        "EQUAL": "РАВНО",
        "LESS": "ПО-МАЛКО",
        "PLUS": "ПЛЮС",
        "Infinite loop": "Безкраен цикъл",
        "Adding icons": "Добавяне на icons",
        "Publishing instantly": "Публикуване веднага",
        "Changing font size only": "Само промяна на font size",
        "Only text": "Само text",
        "A file": "File",
        "Breaking a problem into smaller parts": "Разделяне на проблем на по-малки части",
        "Where it can be accessed": "Къде може да бъде достъпена",
        "Its color": "Нейният цвят",
        "Its icon": "Нейната icon",
        "Its device": "Нейното device",
        "Stops checking once the result is known": "Спира проверката, щом резултатът е ясен",
        "Deletes all conditions": "Изтрива всички conditions",
        "Runs every branch": "Изпълнява всеки branch",
        "Skips compilation": "Пропуска компилация",
        "Queue": "Queue",
        "Stack": "Stack",
        "Tree": "Tree",
        "The condition that stops recursion": "Условието, което спира recursion",
        "The largest array": "Най-големият array",
        "A Boolean operator": "Boolean operator",
        "Arranges values by a rule": "Подрежда стойности по правило",
        "Deletes values": "Изтрива стойности",
        "Creates UI": "Създава UI",
        "Imports modules": "Импортира modules",
        "Something expected to be true before code runs": "Нещо, което се очаква да е вярно преди code да се изпълни",
        "A font": "Font",
        "A device": "Device",
        "The remainder": "Остатъкът",
        "The quotient": "Частното",
        "A string": "String",
        "A Boolean only": "Само Boolean",
        "An unusual input that may break logic": "Необичаен input, който може да счупи logic",
        "A screen edge": "Ръб на екрана",
        "A color": "Color",
        "Describing algorithm growth": "Описване на растежа на algorithm",
        "Drawing circles": "Рисуване на circles",
        "Naming variables": "Именуване на variables",
        "Linear time": "Линейно време",
        "Exponential time": "Експоненциално време",
        "No time": "Без време",
        "Sorted data": "Сортирани данни",
        "Random data": "Случайни данни",
        "A network": "Network",
        "Nodes and edges": "Nodes и edges",
        "Only arrays": "Само arrays",
        "Only views": "Само views",
        "Reusing overlapping subproblem results": "Преизползване на резултати от припокриващи се subproblems",
        "Changing icons": "Промяна на icons",
        "Unexpected state changes": "Неочаквани state changes",
        "All memory use": "Цялото memory use",
        "All UI code": "Целият UI code",
        "All functions": "Всички functions",
        "Output depends on timing of operations": "Output зависи от timing на operations",
        "A fast loop only": "Само бърз loop",
        "A sorting rule": "Sorting rule",
        "A compiler setting": "Compiler setting",
        "Caching previous results": "Кеширане на предишни резултати",
        "Deleting previous results": "Изтриване на предишни резултати",
        "Drawing tables": "Рисуване на tables",
        "Repeated calls have the same effect": "Повторните calls имат същия ефект",
        "Calls always fail": "Calls винаги fail-ват",
        "Calls are random": "Calls са random",
        "Calls require UI": "Calls изискват UI",
        "A model with states and transitions": "Model със states и transitions",
        "A hardware-only feature": "Hardware-only feature",
        "A font system": "Font system",
        "An image type": "Image type",
        "Artificial Intelligence": "Artificial Intelligence",
        "Apple Interface": "Apple Interface",
        "Automatic Internet": "Automatic Internet",
        "App Installer": "App Installer",
        "Manual typing only": "Само ръчно писане",
        "A phone setting": "Phone setting",
        "A design color": "Design color",
        "A button": "Button",
        "A screen layout": "Screen layout",
        "A cable": "Cable",
        "A workout app": "Workout app",
        "A folder name": "Folder name",
        "A compiler": "Compiler",
        "A battery type": "Battery type",
        "Drawing a line": "Рисуване на line",
        "Opening settings": "Отваряне на settings",
        "Saving a password": "Запазване на password",
        "Deleting files": "Изтриване на files",
        "Changing language": "Промяна на language",
        "Only Swift code": "Само Swift code",
        "Binary numbers": "Binary numbers",
        "A device model": "Device model",
        "It predicts from patterns": "Предсказва по patterns",
        "It has no output": "Няма output",
        "It cannot receive input": "Не може да получава input",
        "Making screens blue": "Правене на screens сини",
        "Writing fewer tests": "Писане на по-малко tests",
        "Ignoring users": "Игнориране на users",
        "A model memorizes training data too closely": "Model запаметява training data прекалено точно",
        "A perfect model": "Перфектен model",
        "A UI bug": "UI bug",
        "A battery issue": "Battery issue",
        "Using a trained model to produce output": "Използване на обучен model за output",
        "Deleting training data": "Изтриване на training data",
        "Opening Xcode": "Отваряне на Xcode",
        "A chunk of text": "Парче text",
        "A Swift keyword only": "Само Swift keyword",
        "An image file": "Image file",
        "Skew that can affect model behavior": "Изкривяване, което може да повлияе на model behavior",
        "A compiler warning": "Compiler warning",
        "A network port": "Network port",
        "Checking model performance during development": "Проверка на model performance по време на development",
        "Drawing UI": "Рисуване на UI",
        "Changing fonts": "Промяна на fonts",
        "Connected processing units": "Свързани processing units",
        "App icons": "App icons",
        "File folders": "File folders",
        "Screen pixels only": "Само screen pixels",
        "Representing meaning as numbers": "Представяне на meaning като числа",
        "Creating iOS certificates": "Създаване на iOS certificates",
        "Deleting arrays": "Изтриване на arrays",
        "Making buttons": "Създаване на buttons",
        "A confident but incorrect output": "Уверен, но грешен output",
        "A guaranteed fact": "Гарантиран fact",
        "A UI animation": "UI animation",
        "Learning from labeled examples": "Учене от labeled examples",
        "Learning with no data": "Учене без data",
        "Manual UI layout": "Ръчен UI layout",
        "App Store review": "App Store review",
        "How sure a model is about output": "Колко сигурен е model за output",
        "A view size": "View size",
        "An icon name": "Icon name",
        "A control for randomness": "Контрол за randomness",
        "A hardware sensor only": "Само hardware sensor",
        "A data label": "Data label",
        "A model size": "Model size",
        "Using retrieved context to answer": "Използване на retrieved context за отговор",
        "Training with no data": "Training без data",
        "Only drawing UI": "Само рисуване на UI",
        "Deleting prompts": "Изтриване на prompts",
        "Model behavior using additional training": "Model behavior чрез допълнително training",
        "The screen size": "Размерът на екрана",
        "Evaluating classification results": "Оценяване на classification results",
        "Designing colors": "Дизайн на colors",
        "How many predicted positives were correct": "Колко predicted positives са били правилни",
        "How many files compile": "Колко files се compile-ват",
        "How fast UI draws": "Колко бързо се рисува UI",
        "How large an icon is": "Колко голяма е icon",
        "How many actual positives were found": "Колко actual positives са открити",
        "How many buttons exist": "Колко buttons има",
        "How many files import SwiftUI": "Колко files import-ват SwiftUI",
        "How many views animate": "Колко views animate-ват",
        "How much input a model can consider": "Колко input може да вземе предвид model",
        "The app's main window": "Главният window на app",
        "A SwiftUI modifier": "SwiftUI modifier",
        "A screen brightness value": "Screen brightness value",
        "Measuring output quality against criteria": "Измерване на output quality спрямо критерии",
        "Input that tries to override instructions": "Input, който се опитва да override-не instructions",
        "A Swift function": "Swift function",
        "A layout container": "Layout container",
        "A memory warning": "Memory warning",
        "To reduce harm from mistakes": "За намаляване на вреда от грешки",
        "To slow all apps": "За забавяне на всички apps",
        "To avoid UI": "За избягване на UI",
        "To remove data": "За премахване на data"
    ]
}
